(cl:defpackage skeleton_markers-srv
  (:use )
  (:export
   "SKELETON_LISTENER_SERVICE"
   "<SKELETON_LISTENER_SERVICE-REQUEST>"
   "SKELETON_LISTENER_SERVICE-REQUEST"
   "<SKELETON_LISTENER_SERVICE-RESPONSE>"
   "SKELETON_LISTENER_SERVICE-RESPONSE"
  ))

